### ISSUE TITLE
Problem writing to googlesheets

### ISSUE THREAD

**Issue by jiaoshuo** [tidyverse/googlesheets4#110]
I keep encountering the following errors when I try to write a 360x24 matrix to googlesheets using write_sheet(). 
```r
Error: Expected content type 'application/json' not 'text/html'.
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 408 (Request Timeout)!!1</title>
  <style>...
```

**Comment by jennybc** [comment]
Can I see your exact code?

**Comment by jennybc** [comment]
I am able to write such a sheet. Perhaps you just got unlucky or had a back internet connection.

``` r
library(googledrive)
library(googlesheets4)
#> 
#> Attaching package: 'googlesheets4'
#> The following objects are masked from 'package:googledrive':
#> 
#>     request_generate, request_make

# auth happening in a hidden chunk here
```

``` r
dat <- as.data.frame(matrix(seq_len(360 * 24), nrow = 360))
dim(dat)
#> [1] 360  24
system.time(
  (ss <- sheets_write(dat))
)
#> Creating new Sheet: "steadfast-prawn"
#>    user  system elapsed 
#>   1.835   0.022   3.833

drive_trash(ss)
#> Files trashed:
#>   * steadfast-prawn: 1--JQ9S6QWGnFIwuXvXbRYgxKEs3eN55b6Dpl5rAkmrs
```

<sup>Created on 2020-03-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by ZainWahab** [comment]
@jennybc  I have the same error

`daily<-dbGetQuery(conn = con, statement=dailyq) 
range_write(ss=sid,daily,sheet='Daily',range='A1',reformat = TRUE)`

Error
Editing "PD_Auto"
Writing to sheet "Daily"
Error: Expected content type 'application/json' not 'text/html'.
Editing "PD_Auto"
Writing to sheet "Daily"
Error: Expected content type 'application/json' not 'text/html'.

**Comment by nicholailidow** [comment]
The same issue started happening to me a few days ago.
I've been running a script as a cron job for several months with no problems. The end of the script writes out to 4 google sheets, e.g. write_sheet(d1, ss="XXXXXX", sheet="Sheet1").

Since upgrading to R 4.0, the first write_sheet fails, but the other write_sheet calls go on with no problem. If I manually run the first write_sheet again, it succeeds. 

I get this error for the first write_sheet:
Error: Expected content type 'application/json' not 'text/html'.
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 408 (Request Timeout)!!1</title>
  <style>...

Any thoughts would be appreciated.

Thank you,
Nicholai

**Comment by jennybc** [comment]
Can anyone show me a backtrace? I'd like to know exactly *who* is throwing this error. As in, which function in which package. Functions like `traceback()` and `rlang::last_trace()` will be helpful. An html 408 is not a documented error thrown by Sheets, although I don't deny that you are seeing it. I've just never seen it and we don't handle it because according to the Sheets API docs, this is not possible.

**Comment by jennybc** [comment]
I'm trying to figure out if it's coming from httr or gargle or googlesheets4.

**Comment by jennybc** [comment]
If this conversation continues, the next conversant should open a new issue.

**Comment by nicholailidow** [comment]
@jennybc I opened a new issue. Thank you.

**Comment by chrowe** [comment]
See https://github.com/tidyverse/googlesheets4/issues/155
