### ISSUE TITLE
Make it possible to prioritize reading speed (e.g. read "values only")

### ISSUE THREAD

**Issue by ramirobentes** [tidyverse/googlesheets4#122]
I have a relatively big (50,000 rows and 24 columns) dataset on Google Sheets that I use to feed a Shiny App. I've been using the googlesheets package, which does the job just fine, as it reads the dataset very quickly after loading the Shiny App. However, since googlesheets will stop working in a few weeks (days?), I'm trying to update my app to use googlesheets4. It works just fine with smaller datasets (under 2,000 rows, for example), but it takes a really long time to read the large one, causing the app to not load.

I uploaded a similar dataset to Google Sheets and made it public in order to provide a reprex:
https://docs.google.com/spreadsheets/d/1mnWcn7bd7obaXd05rnXrEtgzMBLdy7ctsYvlQM52W00/edit#gid=1706945294

Using the googlesheets package:

```r
gs_url("https://docs.google.com/spreadsheets/d/1mnWcn7bd7obaXd05rnXrEtgzMBLdy7ctsYvlQM52W00/edit#gid=1706945294") %>%
  gs_read()
# 6.47 sec elapsed
```
Using the googlesheets4 package:
```r
read_sheet("https://docs.google.com/spreadsheets/d/1mnWcn7bd7obaXd05rnXrEtgzMBLdy7ctsYvlQM52W00/edit#gid=1706945294") 
# 288.9 sec elapsed
```

Am i doing something wrong?

Thanks in advance!

**Comment by jennybc** [comment]
First, it turns out the older API and, therefore, googlesheets is going to work for a lot longer than initially advertised.

https://twitter.com/JennyBryan/status/1232346667640188932

I think what you're doing (accessing by ID) might continue working until September 2020.

But yeah we should get you switched over.

---

The original googlesheets reads data according to 3 different mechanisms that differ in speed and features. Approximately, it uses the fastest one with enough features to fulfill your request.

Currently googlesheets4 uses the most featureful reading method ... but also the slowest. But there are endpoints I can hit that are faster. Basically this comes down to getting "values only" or full cell data. Currently I get full cell data because it makes the code simpler, so it's where I started.

So I will edit the title of your issue to request that faster reading methods become exposed.

**Comment by ramirobentes** [comment]
Perfect! Thanks!

**Comment by jennybc** [comment]
Can you explain more about how you are reading this large Sheet? Do you just read a whole worksheet? Or do you specify things like `range` or `skip`? What are the permissions on it (are you sending a token)?

This is part of scoping what a "just read it fast" function would support (from a user's POV). Obviously there will be hard constraints from the other side re: what's possible.

**Comment by ramirobentes** [comment]
Yes, I just read the whole worksheet, without specifying range or skipping rows. It's a private sheet so I have to run `gs_auth(token = readRDS("googlesheets_token.rds"))` before reading it.

**Comment by jennybc** [comment]
If speed is the priority and other things (formatting, automatic date parsing) are not important, I can get sheet values using some special URLs (so bypassing the Sheets API entirely). This csv representation can be read with readr or vroom. And it looks like this will be twice as fast as the result you're seeing with the old package:

```
> bnch
# A tibble: 4 x 13
  expression                            min median `itr/sec` mem_alloc `gc/sec`
  <bch:expr>                          <bch> <bch:>     <dbl> <bch:byt>    <dbl>
1 readr::read_csv(nba_export_url)     3.09s  3.09s     0.323    21.8MB    0.323
2 vroom::vroom(nba_export_url)        2.52s  2.52s     0.397    10.5MB    0    
3 readr::read_csv(nba_datasource_url) 3.14s  3.14s     0.319    24.2MB    0.319
4 vroom::vroom(nba_datasource_url)    2.82s  2.82s     0.355    12.9MB    0    
# … with 7 more variables: n_itr <int>, n_gc <dbl>, total_time <bch:tm>,
#   result <list>, memory <list>, time <list>, gc <list>
```

So I will wrap this up and include in the release.

**Comment by ramirobentes** [comment]
Sounds good! Would that work for private sheets?

**Comment by jennybc** [comment]
> Would that work for private sheets?

Yes I have a way of sending a token, even in this case. It can be sent as a query parameter, which is less than ideal but it works.
