### ISSUE TITLE
Hitting quota limits - how to specify the project ID listed in the google cloud console?

### ISSUE THREAD

**Issue by jzadra** [tidyverse/googlesheets4#139]
I'm running into an issue (expected, since I'm done a lot of `sheets_edit()` calls) where I hit my quota limits:

```
Error: Client error: (429) RESOURCE_EXHAUSTED
 * Either out of resource quota or reaching rate limiting. The client should look for google.rpc.QuotaFailure error detail for more information.
 * Quota exceeded for quota group 'ReadGroup' and limit 'Read requests per user per 100 seconds' of service 'sheets.googleapis.com' for consumer 'project_number:[masked for privacy]’.
```

I have a project set up on the cloud console for googlesheets4 that has had the quotas increased, however after troubleshooting with google I've learned that the project I've increased the quotas on is different than the one that googlesheets4 is using.  The project_number listed above is not listed as a project on the cloud console.

Is there a way to specify a specific google cloud project for use with googlesheets4?  Or on google's end, to edit the project that is being listed in the error  if it isn't being listed?

**Comment by jennybc** [comment]
In order to have your requests logged under your quota-enhanced project, you'll need to bring your own oauth app or use a service token associated with that project.

This is documented here, in gargle, because it works the same across all packages that use gargle for auth:
  * <https://gargle.r-lib.org/articles/get-api-credentials.html>

**Comment by jzadra** [comment]
Thanks!
