### ISSUE TITLE
Add cols() specification

### ISSUE THREAD

**Issue by MonkmanMH** [tidyverse/googlesheets4#156]
Please add the `col_types = cols()` specification, for consistency with {readr}'s [column specification](https://readr.tidyverse.org/reference/cols.html)

Using the example from {googlesheets4} example:

```r
#read_sheet("https://docs.google.com/spreadsheets/d/1U6Cf_qEOhiR9AZqTqS3mbMF3zt2db48ZP5v3rkrAEJY/edit#gid=780868077")

#name sheet to save some copy-paste
gapminder_sheet <- "https://docs.google.com/spreadsheets/d/1U6Cf_qEOhiR9AZqTqS3mbMF3zt2db48ZP5v3rkrAEJY/edit#gid=780868077"

# the plain `read_sheet()`
read_sheet(gapminder_sheet)

```

Example: read_sheet with "year" column specified as integer.

We can use the current {googlesheets4} syntax (see ["Column specification"](https://googlesheets4.tidyverse.org/reference/range_read.html#column-specification)

```r
read_sheet(gapminder_sheet, col_types = "??i???")
```

But for files with many variables, this syntax can be cumbersome and error-prone (particularly if there are a limited number of variables that need specifying).

Adding `col_types = cols()` functionality would solve this challenge, and be consistent with {readr}.

The syntax would thus look like this:

```r
# set "year" as integer
read_sheet(gapminder_sheet, 
           col_types = cols(
             year = col_integer()
             )
           )
```

Currently, this syntax returns "Error: `col_types` must be character: * `col_types` has class 'col_spec'" -- it took me a while to realize that it's an error because {googlesheets4} doesn't recognize the syntax.

Thanks!

**Comment by jennybc** [comment]
The need for a richer column type specification is already being tracked in #51. Right now googlesheets4 only has the "shortcode" style 😔

This is high priority but it's also a nontrivial issue because we need to figure out how to support a common col spec approach across multiple packages (including readxl https://github.com/tidyverse/readxl/issues/198). We don't want to keep implementing it separately in multiple places. It is something on my road map for the coming months, but not at the very top.
