### ISSUE TITLE
Error: 'request_retry' is not an exported object from 'namespace:gargle' 

### ISSUE THREAD

**Issue by mikegunn** [tidyverse/googlesheets4#164]
Hi there, read sheet is throwing up this error, i have tried to install and re-install gargle and i am also using the devtools package (devtools::install_github("tidyverse/googlesheets4",force=TRUE)) which looks to partly install gargle i believe?

> EPL_CARDS<-read_sheet("17gxSsNCJ4nYTV3npmlXXXXXXXX", sheet = "EPL Players" ) (XXXX'd out so my sheet isn't public)
Error: 'request_retry' is not an exported object from 'namespace:gargle'

Sorry if this is vague, there isn't much more to put in the request.

**Comment by mikegunn** [comment]
re-installed googlesheets4 and now working!

**Comment by jennybc** [comment]
`request_retry()` is a gargle function that only exists in a *pull request* in the dev version of gargle, which is used by the *dev* version of googlesheets4.

As it seems you discovered (but perhaps not with full realization), you either need to install googlesheets4 from CRAN and use the official release or you need to do `devtools::install_github("tidyverse/googlesheets4")` in order to pick up the smarts re: installing gargle from a PR. This is a temporary dev situation that is useful to me.

**Comment by DannySmith111** [comment]
Hi Jenny, I was wondering if you could help me re-install googlesheets4. For some reason the sheets_write() function disappeared for me so I am trying to re-install, however I am having issues with the 'glue' package.

Error: Failed to install 'googlesheets4' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘glue’

It also looks like I am having the same for the 'fs' package.

Any idea what to do? I have tried removing the glue package but it says it does not seem to exist.
Thanks!

**Comment by jennybc** [comment]
I suspect you're on Windows and seeing some of its infamous package installation problems.

The problem is described in general here:
https://www.jimhester.com/post/2020-08-20-best-os-for-r/

And here's a thread where we talk about how we usually answer this question:
https://github.com/rstats-wtf/what-they-forgot/issues/62

**Comment by pesavage** [comment]
> `request_retry()` is a gargle function that only exists in a _pull request_ in the dev version of gargle, which is used by the _dev_ version of googlesheets4.
> 
> As it seems you discovered (but perhaps not with full realization), you either need to install googlesheets4 from CRAN and use the official release or you need to do `devtools::install_github("tidyverse/googlesheets4")` in order to pick up the smarts re: installing gargle from a PR. This is a temporary dev situation that is useful to me.




When I try to install this (OSX I get the following error message. This used to work for me back in 2020 but isn't working any more now in May 11 2021. I tried on both RStudio (Version 1.1.383) and base R (R 3.5.3) Any thoughts?

> devtools::install_github("tidyverse/googlesheets4")
Error: Failed to install 'googlesheets4' from GitHub:
  HTTP error 401.
  Bad credentials

  Rate limit remaining: 55/60
  Rate limit reset at: 2021-05-11 08:54:22 UTC

**Comment by pesavage** [comment]
Thanks!
