### ISSUE TITLE
Timeout error 408

### ISSUE THREAD

**Issue by douglascm** [tidyverse/googlesheets4#187]
I've been unable to easely write anything over 500 lines and about 30 columns with current version, 4000 and more was not an issue with 0.1.0.9000 that I had previously installed.
Sometimes it hangs for over a minute then gives me the error, very rarely it works fast.
This was on a 600 Kb object

I'm using 
gs4_auth(email = "my email")
gs4_auth_configure(api_key = "my key")
to login

Since I'm scheduling runs based on this its important to not fail, what can I do besides do a loop with tryCatch?

```(r)
Error: Expected content type 'application/json' not 'text/html'.
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 408 (Request Timeout)!!1</title>
  <style>...

rlang::last_error()
<error/gargle_error_request_failed>
Expected content type 'application/json' not 'text/html'.
<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 408 (Request Timeout)!!1</title>
  <style>...
Backtrace:
  1. googlesheets4::sheet_write(ss = ss, data = res, sheet = "dataset")
  2. gargle::response_process(resp_raw)
  7. gargle:::error_message(resp)
  8. gargle::response_as_json(resp)
  9. gargle:::check_for_json(resp)
 10. gargle:::stop_request_failed(message, resp)
```

**Comment by jennybc** [comment]
> 4000 and more was not an issue with 0.1.0.9000 that I had previously installed.

I don't *think* anything inside googlesheets4 has materially changed in a way that would matter. You could test that by installing an old version, if you really want to know. But I suspect it's something that has changed on the server, which correlates with time and therefore with googlesheets4 versions. There's another issue where someone has noted a new-ish policy (ah, I see you've found #177).

``` r
gs4_auth(email = "my email")
gs4_auth_configure(api_key = "my key")
```

FYI, the API key is only used in the case of de-authorized requests and that can only happen for reading world readable stuff. So if you think you're using your own oauth app and GCP project, you are not. At least, not with these writing operations.

> Since I'm scheduling runs based on this its important to not fail, what can I do besides do a loop with tryCatch?

It's hard to say because it's intermittent and sometimes doesn't fail. I don't think this is anything specific to how we (as in googlesheets4) are communicating with the API. So I would suggest generic advice like write a whole Sheet if you can using `googledrive::drive_upload()`. For appending, I would certainly test chopping the work into smaller pieces and deliberately pausing in between sending chunks. Then, yeah, you may have to resort to catching failure and retrying.

**Comment by douglascm** [comment]
Version 0.1.0.9000 isn't available in CRAN, and the ones available don't have any write functions.

I'm still running that 0.1.0.9000 versions without any issue, never getting the timeout error and pasting information much faster, just tried pasting 5 datasets that all didn't work on the first try or even the second with 0.2.0 that all worked without issues on 0.1.0.9000.
Is there a way to make that version available in cran or git?

Thanks for the reply.

I used the API key since I understood that was a way to get around the Resource Exhausted 429 error. I did kinda managed to get around it with a try/sleep(100s).

**Comment by jennybc** [comment]
> Version 0.1.0.9000 isn't available in CRAN

That's a dev version and, since we don't bump dev version with each commit, it's not really a version, i.e. it does not identify a specific state of the source code.

If you installed it with `devtools::install_github()`, the SHA you installed from is recorded in the installed package.
You can see that in the output of `devtools::session_info()` or like so:
``` r
d <- desc::desc(package = "devtools")
d$get_field("RemoteSha")
#> [1] "df619ce29b722f34e5d5f83e336881f12ab3ed05"
```

> Is there a way to make that version available in cran or git?
Once you have the SHA, you can install from GitHub (and we can actually look at the difference between that and another state):

```
devtools::install_github("OWNER/REPO@SHA")
```

> I used the API key since I understood that was a way to get around the Resource Exhausted 429 error.
But I'm saying we don't send the API key on writes. We can't. You can't write without sending a token. And if we send a token, we never send the API key.

> just tried pasting 5 datasets that all didn't work on the first try or even the second with 0.2.0

The dev version of googlesheets4 uses a dev version of gargle that is equipped with retries. It is solving all of my retry problems. So you might also want to try that (instead of the current CRAN release).

**Comment by douglascm** [comment]
> The dev version of googlesheets4 uses a dev version of gargle that is equipped with retries. It is solving all of my retry problems. So you might also want to try that (instead of the current CRAN release).

I'm sorry but I couldn't find a way for using the retries

**Comment by jennybc** [comment]
> I'm sorry but I couldn't find a way for using the retries

```
devtools::install_github("tidyverse/googlesheets4")
```
installs the dev version of googlesheets4 and a dev branch of gargle. Then use googlesheets4. It is equipped with retries. Make sure to restart R after any package installation, so you can be sure you are using the newly installed version.

**Comment by douglascm** [comment]
the version I was working with has the SHA 20d2d22de09946a4642e92079a46e5934951412a

**Comment by jennybc** [comment]
Interesting! Perhaps I should have thought of this but I had forgotten that googledrive issue. But the 408 timeout that you are seeing is weird and not what I suffer from (and what prompted my work on retries), which is the 429 quota problem.

**Comment by douglascm** [comment]
Quota issue seems easy to work around with sleep(100), that I'm using
already.

**Comment by jennybc** [comment]
>Quota issue seems easy to work around with sleep(100), that I'm using already.

FWIW that is the one that seems to be well handled by dev googlesheets4.
