### ISSUE TITLE
Function to retry if quote limit hit - e.g. RESOURCE_EXHAUSTED error

### ISSUE THREAD

**Issue by JimboMahoney** [tidyverse/googlesheets4#189]
Hi all,

I've been running into a lot of quota limits and since I'm a newbie to both R and Google API / authorisation, I thought I'd post my workaround in case 1) it's useful to others or 2) there is a better solution.

I notice there is a solution posted here - https://github.com/tidyverse/googlesheets4/issues/139 - but I don't understand any of it.

I do have an API key that I can see at https://console.developers.google.com/ and perhaps adding that to my code would improve my quota?

I'm using this to open a browser window to get a token, so maybe I just need to add the api key to this code?

```
if (interactive()){
gs4_auth(
  email = NULL,
  path = NULL,
  scopes = "https://www.googleapis.com/auth/spreadsheets",
  # Get cached secret once - comment out for repeated use locally
  #cache = ".secrets",
  # Use once we have the secret cached
  cache = FALSE,
  use_oob = FALSE,
  token = NULL)
}
```

Maybe I just need to add this line?

`gs4_auth_configure(api_key = "MY_API_KEY")`

Anyway, here is my (no doubt ugly) solution to the issue of occassionally hitting quota limits:

```
Speed_Read <- function(l, ...){
  # Set initial sleep and values
  sleep <- 1
  value <- NULL
  while(is.null(value)){
    try(
      value <- lapply(l, function(x){
        range_read(x, ...)
      })
    )
    Sys.sleep(sleep)
    sleep <- sleep + 1
  }
  return(value)
}
```

Essentially, "Speed_Read()" replaces "range_read()" in the rest of my code and it will continually retry the range_read if there is an error, each time adding a little extra delay until the read is successful.

Hope this is useful to someone or there is some feedback on how to improve this function.

**Comment by jennybc** [comment]
The dev version of googlesheets4 uses a dev branch of gargle that is equipped with retries. I would advise use of that, instead of homegrown functions, in general, because these will both eventually become in released versions on CRAN.

This is happening, because everyone who uses googlesheets4, by default, is sharing the same quota. This sounds wild, but it's true. This is a consequence of us making googlesheets4 "just work" for casual users by having built-in oauth creds.

If you want your own quota, you must either use a service account token or your own oauth creds. Getting your own auth creds is what's recommended (and worked for OP) in #139.

An API key is sent if and only if we are in a deauth'ed state and it will only work for reading world-readable documents. So, sure, you can configure an API key, but what is more useful is to configure your own oauth app, so that the regular tokens you get are associate with your project and you aren't sharing quota with anyone else. Again, that's #139. It looks harder than it is, just because there are several steps.

**Comment by JimboMahoney** [comment]
Thanks Jenny.

I *think* I get it now.

The first part of my code `gs4_auth` is needed to log in to my gmail account, which gives me the correct persmissions to read/write private Google sheets.

However, that is still using googlesheets4 built-in oauth credentials.

Creating a Google Cloud Project (which I had already one, but I think they key step I was missing was to enable the Google Sheets API for it) as per this link:

https://gargle.r-lib.org/articles/get-api-credentials.html

and then using the following R code (from https://gargle.r-lib.org/articles/get-api-credentials.html)

```
google_app <- httr::oauth_app(
  "my-awesome-google-api-wrapping-package",
  key = "MY_CLIENT_ID",
  secret = "MY_SECRET"
)
google_key <- "MY_API_KEY"
gs4_auth_configure(app = google_app, api_key = google_key)
```

Results in a webpage popping up locally with the name of my project instead of the usual "Do you want to allow Tidyverse access?".

I can also see API requests coming into the Google Cloud Platform Dashboard.

Thanks!

**Comment by jennybc** [comment]
Yes! Sounds like you are on the right track for using your own credentials.

**Comment by JimboMahoney** [comment]
Thanks.

I've also realised it's a LOT faster to read the entire sheet using googledrive and then readxlsx from openxlsl.

I'll still use googlesheets to write data back to the sheet, rather than openxlsx and then upload using googledrive because I want to maintain the permissions on the googlesheet, which I don't seem to be able to do when I upload a sheet using googledrive.

**Comment by jennybc** [comment]
I'd be interested to hear how it goes with `googlesheets4::range_speedread()`

https://googlesheets4.tidyverse.org/reference/range_speedread.html

In principle, that should be faster than exporting to local xlsx.

Re: uploading to an existing file id, are you using `googledrive::drive_update()`?

https://googledrive.tidyverse.org/reference/drive_update.html

**Comment by JimboMahoney** [comment]
Thanks for all your help Jenny!

Re: `speedread()` - since I'm making about 30 (currently) "reads" (since my data is in various sheets and ranges), I'm guessing that `read.xlsx()` after a single googledrive download of the Google Sheet will still be faster, right?

I was using `drive_upload()`, which of course was uploading a "new" file.
In much the same way as the reads, I'm doing about 10 or so separate writes, so writing to a local workbook (xlsx) and then updating the Googlesheet will probably be faster - I'll give that a whirl.

**Comment by jennybc** [comment]
> Re: range_speedread() - since I'm making about 30 (currently) "reads" (since my data is in various sheets and ranges), I'm guessing that read.xlsx() after a single googledrive download of the Google Sheet will still be faster, right?

Oh, that changes things, yeah (c.f. http://norvig.com/21-days.html#answers). Bringing all of the data local, at once, may indeed make the most sense in that case. I am, of course, predisposed to readxl over openxlsx, for obvious reasons 😅

Re: `drive_upload()` / `drive_update()` / `drive_put()`: you will only have these options if you're uploading the entire spreadsheet. If you need to address different sheets or ranges, then you must use the Sheets API and, therefore, googlesheets4 instead of googledrive.

**Comment by FahmiRR** [comment]
Hi All,

I wanted to know whether this code below can be deployed in shinyapps.io? I have tried following all the steps but still no luck

```
google_app <- httr::oauth_app(
  "my-awesome-google-api-wrapping-package",
  key = "MY_CLIENT_ID",
  secret = "MY_SECRET"
)
google_key <- "MY_API_KEY"
gs4_auth_configure(app = google_app, api_key = google_key)
```

So far I was able to connect using solution in #184. But apparently, if multiple user trying to access my apps sometimes it throws `Client error: (429) RESOURCE_EXHAUSTED` error. 

Looking at this [issue](https://github.com/r-lib/gargle/issues/146#issuecomment-645449077) @jennybc suggest to use own API key and/or OAuth app

Any help would be appreciated, Thank you

**Comment by JimboMahoney** [comment]
@FahmiRR 

I had exactly the same problem - I'm also deploying via ShinyApps.io and I now have a working solution that uses my own credentials, rather than the built-in googlesheets4 one that every user is sharing, hence the occassional 429 errors.

Here is my post on stackoverflow, with the solution, as well as links to the "a-ha!" resources that helped me conceptualise and execute what was required.

[https://stackoverflow.com/questions/65051305/struggling-to-use-my-own-api-key-with-googlesheets4-in-shinyapps-io](url)

**Comment by FahmiRR** [comment]
This works perfectly! Thanks a lot! @JimboMahoney 

So the part that I have missed the whole time is giving the service account access to the Google Sheet(s). Although its kinda weird because the Google Email that I have been using for GCP was already have access to the Sheet.

**Comment by JimboMahoney** [comment]
@FahmiRR 

Cool! Glad it helped!

I was confused too, and I still don't fully understand the whole access token / service account / API / oauth thing! (Although I do understand that googlesheets works "out of the box" because it has all these things set up already, which is why it sometimes hits limits.

I'm very grateful to @jennybc for creating / maintaining it!

**Comment by jennybc** [comment]
> So the part that I have missed the whole time is giving the service account access to the Google Sheet(s).

I think @daattali also got stuck and eventually unstuck on this. If someone makes a PR to the place(s) where you think this advice should go, I'm open to it.

To me, it's obvious that the service account will need to have relevant permissions for the Sheet. But I've also had to internalize a lot of auth details that gargle is trying to spare other developers from learning. So I am getting the message that this is *not* obvious to others.

**Comment by daattali** [comment]
Here's my comment on this topic from a month ago that @jennybc is referring to https://github.com/tidyverse/googlesheets4/issues/170#issuecomment-729823524 

I'm not sure where to add this information to because "make the service account write permissible to the google sheet" is specific to this package, but the instructions that I ended up using are from gargle: https://gargle.r-lib.org/articles/get-api-credentials.html#service-account-token-1 So I'm not sure how this advice works for any other gargle packages.

This may be slightly off topic, but I think it would be helpful to add documentation directly to this package for how to use googlesheets4 in shiny. I found that there was a lot of clicking on different links, jumping around to different packages and different vignettes, reading a lot of information that I wasn't sure if is relevant or not, and trying many different things, until finally landing on what actually worked.

**Comment by jennybc** [comment]
A big update to gargle, related to Shiny, is on the horizon. Once that's merged and the dust has settled, yeah it would make sense to write a vignette and/or provide some sample apps.

**Comment by daattali** [comment]
So happy to hear :) Would this include what we briefly discussed half a year ago: allowing users of a shiny app to use their own Google account instead of the shiny app's developer's Google account? I can't remember where we mentioned that

**Comment by jennybc** [comment]
> allowing users of a shiny app to use their own Google account instead of the shiny app's developer's Google account

Yes, absolutely.
