### ISSUE TITLE
Error: OAuth2 flow requires an interactive session

### ISSUE THREAD

**Issue by johnbde** [tidyverse/googlesheets4#190]
Thanks for this package. I am running the code below in leanrr (rmarkdown) it throws the error - Error: OAuth2 flow requires an interactive session. It works on my local machine but does not work in docker container. Surprisingly this works on shiny app even in docker container (same config of docker and packages). I have **.secrets** folder where rmarkdown and app file is stored.

```
    gs4_deauth()

  # designate project-specific cache
  options(gargle_oauth_cache = "./.secrets")

  # trigger auth on purpose --> store a token in the specified cache
  drive_auth(cache = "./.secrets", email = "xxx@gmail.com")

  gs4_auth(token = drive_token())
```

trying token_fetch()
trying credentials_service_account()
Error: Argument 'txt' must be a JSON string, URL or file.
trying credentials_app_default()
trying credentials_gce()
trying credentials_byo_oauth()
Error: inherits(token, "Token2.0") is not TRUE
trying credentials_user_oauth2()
Gargle2.0 initialize
attempt from: googledrive
adding 'userinfo.email' scope
loading token from the cache
no matching token in the cache
initiating new token
Error: OAuth2 flow requires an interactive session
Warning: Error in : Can't get Google credentials.
Are you running googledrive in a non-interactive session? Consider:
  * `drive_deauth()` to prevent the attempt to get credentials.
  * Call `drive_auth()` directly with all necessary specifics.
  * Read more in: https://gargle.r-lib.org/articles/non-interactive-auth.html

**Comment by jennybc** [comment]
First a bit of streamlining advice, because I think it's easier to understand and maintain when there's no unnecessary code:

```
gs4_deauth()   # delete this line, it's not doing anything

options(gargle_oauth_cache = "./.secrets")   # I would remove the leading `./` but that doesn't really matter

drive_auth(cache = "./.secrets", email = "xxx@gmail.com") # remove the `cache = ...` part, you did that in previous line
```

As for the problem, we know it's `no matching token in the cache`.

I would troubleshoot by making sure it's finding the cache and make sure the cache holds what you expect. In the problematic context, interactively or with print debugging:

  * Confirm working directory
  * Confirm that `.secrets` is a folder, in the current working directory
  * List the contents of `.secrets`

**Comment by jennybc** [comment]
This one went silent.
