### ISSUE TITLE
Return indicator of API success/failure from sheet_ functions?

### ISSUE THREAD

**Issue by sacrevert** [tidyverse/googlesheets4#194]
This is a feature suggestion, although it may be redundant, as I am new to googlesheets4/API stuff.

I am looking to deploy a questionnaire using RShiny/gs4, and have an app working on my local computer using the non-interactive auth approach. However, I would like to also include a `while() { try() }` statement so that any API call fails are caught, but in this case the sheet already exists, so I cannot monitor for the creation of a sheet object using `is.null()` in the while clause. For example, in the below code example from my Shiny app, I need to monitor something else indicating success in the `while()` function to stop just the writing of 6 identical rows, or 6 pointless overwrites.

Looking at the code of `sheet_write()` or `sheet_append()` I was wondering whether it would be possible for the functions to optionally return some token of success (e.g. from `gargle::response_process()` so that the success of the call (or otherwise) can also be monitored within the `while()` function.

```r
server <- function(input, output, session) {
observeEvent(input$submit, {
    
    if(!imgID() %in% so_far$rand_id){ ## if new submission, just append answer
      
      x <- ids[ids$rand_id == imgID(), ]
      x$q1<- input$q1
      x$q2<- input$q2

      attempt <- 1
      while( attempt <= 6 ) { ## monitor something else to indicate success/failure here?
        attempt <- attempt + 1
        try(
          sheet_append(sheet_id, x, sheet = "Sheet1")
        )
      } 

    } else {
      # else just overwrite the specific updated row, but then rewrite all rows
      so_far[so_far$rand_id == imgID(),
           c('q1', 'q2')] <- list(input$q1,
                                           input$q2)
      
      attempt <- 1
      while( attempt <= 6 ) { ## also monitor something else to indicate success/failure here
        attempt <- attempt + 1
        try(
          sheet_write(so_far, ss = sheet_id, sheet = "Sheet1")
        )
      } 
}
```
Apologies if I am trying to do something stupid, or if this is dealt with elsewhere.

**Comment by sacrevert** [comment]
OK, this was a stupid question, I see that if I assign the `sheet_write()` and `sheet_append()` to objects, then sheet_ids are returned which I can then monitor. Thanks for a great package anyway.

**Comment by jennybc** [comment]
Some quick thoughts (I see you've closed this, but these still hold):

* Dev googlesheets4 uses dev gargle, which has built-in retries and, in my hands, has resolved almost all of my retry problems, i.e. where we hit "too many requests" or sporadic 500 and above errors. So perhaps you should use that instead of a DIY approach. Both will eventually be released to CRAN.
* Why are you not using `tryCatch()`? If you do something like this again, I would read the [section of Advanced R on `tryCatch()` applications](https://adv-r.hadley.nz/conditions.html#condition-applications) and use the patterns you see there. (But I don't think you need to use `try()` or `tryCatch()` in this case.)

**Comment by sacrevert** [comment]
Thanks @jennybc , appreciate the time you took to comment.
