### ISSUE TITLE
API Discovery Service

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googlesheets4#2]
From @craigcitro

https://developers.google.com/discovery/v1/type-format

**Comment by jennybc** [comment]
Discovery document for Drive

https://www.googleapis.com/discovery/v1/apis/drive/v3/rest

**Comment by StevenMMortimer** [comment]
@jennybc Please let me know if you'd like help rebooting V4 of Sheets. I have a script that reads the [discovery document](https://sheets.googleapis.com/$discovery/rest?version=v4) and converts it to functions in roxygen format. If the API ever changes, I just re-run the script and my package functions get updated to match. For example, I re-ran today and noticed that Google added a `titleTextPosition` attribute to objects of type `BasicChartAxis` so that goes into the function that allows you to create basic chart axes. 

<img width="829" alt="screen shot 2018-04-12 at 6 29 31 pm" src="https://user-images.githubusercontent.com/5299737/38707513-9dfd6c3c-3e7f-11e8-9cc5-27eb4f3a3cd1.png">

I think it would be great to port functions from the API into R as close as possible to their Google equivalents and then write some wrapper functions around these base components to match the typical style you see in **googlesheets** today. I wrapped a bunch of these V4 functions a year ago as an example of what I was thinking in https://github.com/jennybc/googlesheets/pull/304.

**Wrapped Functionality**
https://rawgit.com/reportmort/googlesheets/sheets-v4/vignettes/sheets-v4-functionality.html
 * Cut, Copy, Paste, PasteSpecial
 * Insert or Delete Rows, Columns, or Cells
 * Insert or Clear Notes
 * Named Ranges (Create, Read, Update, Delete)
 * Protected Ranges (Create, Read, Update, Delete)
 * Basic Filters (Set, Clear)
 * Merge Cells (Merge, Unmerge)
 * Clear Cells
 * Autofill

**Comment by jennybc** [comment]
The design supported by gargle does incorporate the Discovery Document.

@StevenMMortimer Let's keep your wish list in mind, once googlesheets4 gains edit capacity. I think the initial CRAN release will be "read only", just to get the ball rolling. There are lots of UI issues to think through as I add the ability to create and modify things.  I'm closing this issue but acknowledge those are all good ideas going forward.
