### ISSUE TITLE
Suggestion: add alias `sheet_read()` to match all other `sheet_*` functions

### ISSUE THREAD

**Issue by daattali** [tidyverse/googlesheets4#201]
After learning that I use `sheet_append()` and `sheet_write()` to write data, it's natural to expect `sheet_read()` to read data. Renaming would clearly be a terrible breaking change, but perhaps adding an alias and referring to the new name in documentation would achieve better consistency?

**Comment by jennybc** [comment]
There was a big renaming between the initial version and v0.2.0, because it was clear there had to be an actual principled system of names.

The function names are now therefore result of much analysis and the rationale is laid out in a few places:

https://github.com/tidyverse/googlesheets4/blob/master/NEWS.md#function-naming-scheme

https://googlesheets4.tidyverse.org/articles/articles/function-class-names.html

I know what you're getting at but `read_sheet()` truly is `range_read()` (those 2 are synonyms) because you are reading a *range*. Yes, sometimes that range only specifies the worksheet, because that is a valid range, albeit partially specified. But the fundamental nature of the function is to read a range.
