### ISSUE TITLE
How to complete gs4 auth () function?

### ISSUE THREAD

**Issue by SebastianJHM** [tidyverse/googlesheets4#226]
Hi, thanks to the googlesheets4 team, it's an excellent library.
I am new to this world of APIs and I have not found much information about it.
My intention is to write a shiny application that writes data in a spreadsheet, but I don't know how to authenticate with Gargle, that is, I don't even know how to extract the token that gives the application permissions to access the file or how to use it. . I don't know if I have to extract it using GCP or from Drive. I would like to know how to fill the gs4_auth () to be able to read and write in the spreadsheet. I should clarify that I would like only the application to have the permissions to access the data. Thank you very much in advance and apologies if it is too obvious.

**Comment by jennybc** [comment]
I think, like @cpilat97's example, that you @SebastianJHM should use a service account. This requires some setup, which will be unfamiliar and perhaps uncomfortable at first, but then you will have a robust auth solution for your app.

The links above are sound re: how to get a service account and then how to put its credentials into force.

Remember that you will need to explicitly give this new service account write permission on the target Sheet. The service account won't somehow inherit these privileges automagically, simply because *you* have such privileges and you are associated with the GCP project that owns the service account. It doesn't work that way, but this appears to be a common gotcha.
