### ISSUE TITLE
429 errors

### ISSUE THREAD

**Issue by bmschmidt** [tidyverse/googlesheets4#256]
Thank you for this extremely well documented and conceived package.

One slight issue. After using it for a few days I started getting some 429 errors without initially understanding why (I was making less than one read call per second). After poking around in my own GCP account for a bit, I realized that it's presumably the googlesheets4 package overall that's getting rate-limited.

I suspect that nothing needs to happen, but in the event that you need to apply for an increase in API rates from Google I figure having an issue to point to couldn't help.

It's also possible it might help a bit to wrap the `gargle` error message [here](https://github.com/tidyverse/googlesheets4/blob/1ebcf5f40071d3fef69d16ec9b3c39be06bb48e0/R/request_make.R#L47) with the text in the docstring above it, because other users might follow my error in thinking it it's their *personal* account that's getting rate limited, not the `googlesheets4` account.

```
#' Note that the "project" here means everyone using googlesheets4 who hasn't
#' configured their own OAuth app. This is potentially a lot of users, all
#' acting independently.
```

**Comment by jennybc** [comment]
These packages (gargle, googledrive, googlesheets4) are generally getting better at transmitting error details from Google and that is my focus, i.e. I'm trying not to special case any thing, because API tends to change out from under you. So I'll keep an eye out for ways to improve things, but I don't see a concrete action item right now.
