### ISSUE TITLE
Can't get Google credentials after upgrading to R 3.6

### ISSUE THREAD

**Issue by karawoo** [tidyverse/googlesheets4#27]
After upgrading to R 3.6.0, code that used to work to access a sheet now throws an error. The error message recommends calling `sheets_auth()` directly, which results in the same error. For some reason it seems to think I am not in an interactive session, but I am. I've run into this now on two separate machines (both macs). I know googlesheets4 is still in the "experimental" phase, so maybe I've just hit a sort of development pothole here, but hopefully this report is useful!

``` r
library("googlesheets4")

dat <- read_sheet("https://docs.google.com/spreadsheets/d/1D5azLr6zO_KgvW-0Xilj4B422RR1PV8X-RqgsYcROEY/edit?usp=sharing", sheet = 1)
#> Error: Can't get Google credentials.
#> Are you running googlesheets4 in a non-interactive session? Consider:
#>   * `sheets_deauth()` to prevent the attempt to get credentials.
#>   * Call `sheets_auth()` directly with all necessary specifics.

sheets_auth()
#> Error: Can't get Google credentials.
#> Are you running googlesheets4 in a non-interactive session? Consider:
#>   * `sheets_deauth()` to prevent the attempt to get credentials.
#>   * Call `sheets_auth()` directly with all necessary specifics.
```

<sup>Created on 2019-06-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       macOS Mojave 10.14.5        
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/Los_Angeles         
#>  date     2019-06-07                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package       * version    date       lib
#>  askpass         1.1        2019-01-13 [1]
#>  assertthat      0.2.1      2019-03-21 [1]
#>  backports       1.1.4      2019-04-10 [1]
#>  callr           3.2.0      2019-03-15 [1]
#>  cellranger      1.1.0      2016-07-27 [1]
#>  cli             1.1.0      2019-03-19 [1]
#>  crayon          1.3.4      2017-09-16 [1]
#>  curl            3.3        2019-01-10 [1]
#>  desc            1.2.0      2018-05-01 [1]
#>  devtools        2.0.2      2019-04-08 [1]
#>  digest          0.6.19     2019-05-20 [1]
#>  evaluate        0.14       2019-05-28 [1]
#>  fs              1.3.1      2019-05-06 [1]
#>  gargle          0.1.3.9000 2019-06-07 [1]
#>  glue            1.3.1      2019-03-12 [1]
#>  googlesheets4 * 0.0.0.9001 2019-06-07 [1]
#>  highr           0.8        2019-03-20 [1]
#>  htmltools       0.3.6      2017-04-28 [1]
#>  httr            1.4.0      2018-12-11 [1]
#>  jsonlite        1.6        2018-12-07 [1]
#>  knitr           1.23       2019-05-18 [1]
#>  magrittr        1.5        2014-11-22 [1]
#>  memoise         1.1.0      2017-04-21 [1]
#>  openssl         1.4        2019-05-31 [1]
#>  pkgbuild        1.0.3      2019-03-20 [1]
#>  pkgload         1.0.2      2018-10-29 [1]
#>  prettyunits     1.0.2      2015-07-13 [1]
#>  processx        3.3.1      2019-05-08 [1]
#>  ps              1.3.0      2018-12-21 [1]
#>  purrr           0.3.2      2019-03-15 [1]
#>  R6              2.4.0      2019-02-14 [1]
#>  Rcpp            1.0.1      2019-03-17 [1]
#>  remotes         2.0.4      2019-04-10 [1]
#>  rlang           0.3.4      2019-04-07 [1]
#>  rmarkdown       1.13       2019-05-22 [1]
#>  rprojroot       1.3-2      2018-01-03 [1]
#>  sessioninfo     1.1.1      2018-11-05 [1]
#>  stringi         1.4.3      2019-03-12 [1]
#>  stringr         1.4.0      2019-02-10 [1]
#>  testthat        2.1.1      2019-04-23 [1]
#>  usethis         1.5.0      2019-04-07 [1]
#>  withr           2.1.2      2018-03-15 [1]
#>  xfun            0.7        2019-05-14 [1]
#>  yaml            2.2.0      2018-07-25 [1]
#>  source                                  
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  Github (r-lib/gargle@adedf89)           
#>  CRAN (R 3.6.0)                          
#>  Github (tidyverse/googlesheets4@626b403)
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#>  CRAN (R 3.6.0)                          
#> 
#> [1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

</details>

**Comment by leerssej** [comment]
A breaking change appeared when I updated my gargle package.
I can't get the basic functions on the documentation to work.
for example `token_fetch()` and `sheets_auth(path = 'path/to/my/json_key.json')` don't seem to be getting the necessary results back.
```
 > token_fetch()   
NULL
> sheets_auth(path = 'path/to/my/json_key.json')
Error: Can't get Google credentials.
Are you running googlesheets4 in a non-interactive session? Consider:
  * `sheets_deauth()` to prevent the attempt to get credentials.
  * Call `sheets_auth()` directly with all necessary specifics.
```
Even though the key seems to be functioning correctly in gargle.
```
> gargle::oauth_app_from_json(path = '/path/to/my/json_key.json')
<oauth_app> schematize
  key:    245243539368-q6s380cjqgupovpra3tn2sm4r74j0c9c.apps.googleusercontent.com
  secret: <hidden>
```

Everything worked great before I clicked `Check For Package Updates...` 😞

**Comment by karawoo** [comment]
Looking back at this, I forgot to add that calling `sheets_deauth()` did restore my code to a working state.

**Comment by leerssej** [comment]
Thank you for the quick mention of a helpful resolution. Unfortunately that doesn't seem to to fix the issue now. It seems to be that the workplace authorization isn't wired in yet? per this issue: https://github.com/tidyverse/googlesheets4/issues/24
Just going to have go with this `patch` for now, though will just head back to give the olde googlesheets a try first/

**Comment by leerssej** [comment]
Woohoo! 
I finally found a way to get `googlesheets4::sheets_auth()` c/o `gargle::token_fetch()` c/o  `httr` to choke down my credentials and yield up the googlesheet contents directly into a dataframe. 

The simplest method I found was to pull down an private key for a new project in my google developers console. Then made sure to share it with the project's email! (see Vincent Shield's clear and concise [walkthrough of the process for our sibling language](https://medium.com/@vince.shields913/reading-google-sheets-into-a-pandas-dataframe-with-gspread-and-oauth2-375b932be7bf)

Then one can reference the path to the key in a call (like so) to `sheets_auth(path = "/theplace/notintherepo/whereIstorekeys/mygoogssheetreader-w3r234adfa342we.json")`  
or since this googlesheet for me is a bit of a core page for the moment, I just tucked the path into my `.Renviron` file under the googsAppCreds default entry like so: `GOOGLE_APPLICATION_CREDENTIALS='/theplace/notintherepo/whereIstorekeys/mygoogssheetreader-w3r234adfa342we.json'` where another gargle function happens to hoover up all the essential details anyway. 

Either way, now that I have my credentials all loaded in, I am free to `read_sheet()` away. 

Thank you very much @jennybc for writing such beautifully clear code, including adding/keeping your build notes/thoughts in the repo along with all the annotations, documentation, and vignettes.

**Comment by jennybc** [comment]
Somehow I sort of missed the start of this thread (maybe I read a notification while I was travelling, then forgot to come back).

gargle has been changing rapidly in the past few weeks and I was most diligent about keeping googledrive and bigrquery sync'ed up, because they are on CRAN already and will be re-released very soon. But I was less diligent with googlesheets4. My guess is that the peculiarities noted above come from being in some regrettable state where the HEAD of gargle and googlesheets4 are not compatible. So "development pothole" as @karawoo said.

I believe everything is synced up now: CRAN gargle and dev googlesheets4 should be working together. This is true for me.

@leerssej Glad to hear you've discovered some of the other auth flows that work now and that they do work! But I think you should also be able to use OAuth2 again, if you make sure to have CRAN gargle and update to HEAD of dev googlesheets4. You might need to re-auth once.

My intention is to release bigrquery soon (tomorrow?), then googledrive, and then googlesheets4. Hopefully all without updating gargle again. So the time of rapid change is over.

**Comment by giocomai** [comment]
I know this is closed, but for reference, if anyone who's been using the dev version of either `googlesheets4` or `googledrive` in the past months gets back to this `Error: Can't get Google credentials.` with no evident way out, the only thing that did it for me was to remove/rename the default folder where gargle stores service account tokens (`~/.R/gargle`). `*_deauth()` and such had no effect for me, and it took me a while to realise `gargle` does not cache data in the current working directory or current project folder.

**Comment by ericcrandall** [comment]
I'm encountering this issue again after upgrading to R 4. Going to open a new issue.
