### ISSUE TITLE
`sheets_auth` doesn't work with a token created with `googleAuthR` package (Shiny)

### ISSUE THREAD

**Issue by jjankowiak** [tidyverse/googlesheets4#66]
I want to create an shiny app that analyses some data from a google sheet. It will be deployed on the server. The sheet is only available for users within the company, so as far as as understood from all the other issues I have read, I have to implement "per-user" authentication process in shiny app and I can do it using `googleAuthR` package. This is what I tried:

```
options("googleAuthR.scopes.selected" = c("https://www.googleapis.com/auth/spreadsheets.readonly"))
options("googleAuthR.webapp.client_id" = "<MY_CLIENT_ID>")
options("googleAuthR.webapp.client_secret" = "<MY_CLIENT_SECRET>")
options(shiny.port = 8787)

library(googleAuthR)
library(googlesheets4)
library(shinyjs)


ui <- shinyUI(navbarPage(title = 'sample_app',
                         tabPanel(
                           useShinyjs(),
                           googleAuthUI('gauth_login'),
                           tableOutput('test')
                         )
))

server <- function(input, output, session) {
  access_token <- callModule(googleAuth, "gauth_login")

  read_my_sheet <- function() {
    fil <- access_token()
    sheets_auth(token = fil, scopes = "https://www.googleapis.com/auth/spreadsheets.readonly",
                cache = FALSE, use_oob = FALSE)
    read_sheet("<MY_SHEET_ID>")
  }

  output$test <- renderTable({
    read_my_sheet()
  })
}

shinyApp(ui, server)
```
Unfortunately, when launching the app the first that appears is again a window that asks for authentication by Tidyverse API package. Is there something I'm doing wrong or is it a bug? I want to launch the app, click on the sign-in button and then use the token to read a sheet.

**Comment by jennybc** [comment]
@MarkEdmondson1234 In this awkward period, before gargle really has a nice Shiny story (https://github.com/r-lib/gargle/issues/14), do you have anything useful to suggest here?

@jjankowiak It feels like you might be able to simplify things. Could you make this Sheet readable by "anyone with the link"? And then not publicize the link / Sheet ID anywhere? Then your app is, in theory, the only portal by which the Sheet is really exposed. Depending on what is in it, this might be secure enough? It is definitely security-through-obscurity, though.

**Comment by MarkEdmondson1234** [comment]
If only your employees have access to the Shiny server, then the easiest would be to authenticate with a separate (yours? a service account?) user for your private Google Sheet, and use that auth with the Shiny app embedded in.

Otherwise, if its a public URL but you need authorization before its being shown, then the `gar_shiny_*` family of functions of `googleAuthR` will work, as they rely on creating a login Shiny app to create your token before your Shiny app proper loads, but then that token is available in your main Shiny app and should work as it does locally.

The example here works with a Google Drive API created manually, but it should (untested though) work with any `gargle/httr` based auth - https://code.markedmondson.me/googleAuthR/articles/google-authentication-types.html#gar_shiny_-functions-example

**Comment by jennybc** [comment]
I consider this matter as being tracked by https://github.com/r-lib/gargle/issues/14
