### ISSUE TITLE
Interface questions re: sheets_create() and sheets_write()

### ISSUE THREAD

**Issue by jennybc** [tidyverse/googlesheets4#69]
`sheets_create()` and `sheets_write()` (which will be aliased to `write_sheet()`) are the first 2 writing functions to roll out (still very alpha).

ATM `sheets_create()`'s signature is like so:

```
sheets_create <- function(name, ..., sheets = NULL) {...}
```

Some usage might look like so:

``` r
(ss <- sheets_create("foofy-foofy", sheets = list(iris = iris, mtcars = mtcars)))
#>   Spreadsheet name: foofy-foofy
#>                 ID: 1xUf42Net8e8oZ_SLaTB6eEsNGr61T4m7eR-B9o0HwRU
#>             Locale: en_US
#>          Time zone: Etc/GMT
#>        # of sheets: 2
#> 
#> (Sheet name): (Nominal extent in rows x columns)
#>         iris: 151 x 5
#>       mtcars: 33 x 11
```

`sheets_create()` creates an entirely new (spread)Sheet and, optionally, populates one or more (work)sheets with data, provided as a named list of data frames via `sheets`. Again, this whole interface is very much in flux.

`sheets_write()` looks like this right now:

``` r
sheets_write <- function(data, ss, sheet = NULL, skip = 0, na = "") {...}
```

where `data` is a data frame, `ss` must be an existing (spread)Sheet, and `sheet` must refer to an existing (work)sheet by name or position.

Some usage looks like:

``` r
> (ss <- sheets_write(ChickWeight, ss = ss, sheet = "whatever"))
Writing to 'finally-writing'
Writing to sheet "whatever"
  Spreadsheet name: finally-writing
                ID: 1Yy77dNjJWPvJFx7ENAQOPhotQMNaZ-5MAL2UDed9i1c
            Locale: en_US
         Time zone: Etc/GMT
       # of sheets: 2

(Sheet name): (Nominal extent in rows x columns)
        iris: 5 x 3
    whatever: 579 x 4
```

**What is the primary argument of `sheets_create()`?**
Is it the `name` of the new (spread)Sheet? *current reality*
Or should it be the data (the data frame or named list of data frames)?

Elsewhere, @Hadley indicated he thinks the primary input of `sheets_create()` should be the data. Possibly because I alluded to `writexl::write_xlsx()`, `openxlsx::write.xlsx()` and all the `write.*()` and `readr::write_*()` functions. But maybe `sheets_write()` is the function to compare to those?

Quandary:

`sheets_create()` and `sheets_write()` don't map well onto other `write*()` functions that create a resource (a file) and write data into it, in one fell swoop. It's more like creating a connection and then writing to it.

**Comment by behrman** [comment]
It may be easier for users to understand if `sheets_create()` functioned like `googlesheets::gs_new()`, simply creating a spreadsheet and returning an object to access to it.

Writing could then be done with `sheets_write()`. This could look like the `write*()` functions. Its arguments could be as @hadley suggested with the first argument being data, so that it would work well with pipes.

**Comment by jennybc** [comment]
Yeah @Hadley suggested this as well. The downsides to doing (only) this are:

  * You can't create a Sheet with no worksheets. So if you just create, you get saddled with Sheet1, consisting of (empty) 1000 rows by 26 columns.
  * The "create then add worksheet(s)" workflow makes considerably more API calls. Perhaps most people don't care much about performance, but it's worth noting.

In any case, this is why I want it to be *possible* to send initial data at the moment of creation.

**Comment by behrman** [comment]
I see your point. If you'd like for it to be _possible_ to send initial data at the moment of creation, the question is whether this would be best in `sheets_create()` or `sheets_write()`. You could consider having the `ss` argument of `sheets_write()` having a default `NULL`, in which case a new spreadsheet would be created. A downside of having `sheets_write()` do creation is that it would have to return the object for the created spreadsheet, and the behavior of the `write_*()` functions is to return the data.

One thing to consider in your design is whether the spreadsheet object is changed by writing, such as the list of worksheets, and if the user will need to get the new object in order to work with the spreadsheet. This is the case with `googlesheets` and can be a source of confusion. Would it be possible to use a pointer to the changing object, so that users can use the same pointer after doing operations on the spreadsheet?

**Comment by jennybc** [comment]
> You could consider having the `ss` argument of `sheets_write()` having a default `NULL`, in which case a new spreadsheet would be created.

But what would it's `name` be? I've learned from google drive that it's **very easy** to help people create a multiple files with exactly the same name, which leads to downstream agony rather quickly. That's why currently -- if user doesn't give me a Sheet to operate on -- they must at least specify the `name` of the new Sheet.

> One thing to consider in your design is whether the spreadsheet object is changed by writing, such as the list of worksheets, and if the user will need to get the new object in order to work with the spreadsheet. 

googlesheets (the original) always returns the current object, so the intended workflow is to write back into a local object, as you mutate a Sheet. That keeps the local info current (unless someone else is editing the same Sheet!). So far that's the current plan for googlesheets4 as well. Otherwise, we have to 1) switch to R6 and/or 2) build in some sort of auto-refresh (which implies one or more API calls) each time the object is inspected. So far, I haven't felt like this particular issue merits such a thorough response.

**Comment by behrman** [comment]
A common feature of both the `write_*()` mental model and the connection mental model is that the path / connection doesn't change, and the variables storing these don't need to be updated.

I don't know how hard it would be, but I think there would be advantages if in googlesheets4 `ss` didn't need to be updated. Otherwise, users who don't understand that they need to update, or who forget to, could run into frustrating problems.

I'm mostly used to either functions with no side effects or functions that are only for side effects. When I read the help page of, for example, `gs_edit_cells()`, I didn't read below the arguments section to see the examples. It took some time to discover that the function calls changed `ss`, and I didn't realize that the functions returned the new changed `ss`. (To be honest, after looking at the examples, I'm finally understanding the intended workflow for the first time!)

I agree with the desirability of mirroring the familiar `write_*()` mental model, but for `ss` to fill the same role as `path` I think it would need to not change. Perhaps you could add a level of indirection so that `ss` is a static pointer to the changing object.

**Comment by jennybc** [comment]
> A common feature of both the write_*() mental model and the connection mental model is that the path / connection doesn't change, and the variables storing these don't need to be updated.
>
> ...  but for ss to fill the same role as path I think it would need to not change

Currently googlesheets4 is built around the Sheet's ID. Which is static / unchanging. So it is like a path. I don't really follow this line of push back.

With, e.g., `sheets_get()`, one can obtain metadata on a Sheet. Kind of like storing the number of lines in a file and its permissions at a specific moment in time. And in both cases, the metadata can become out-of-date, but the embedded path (ID in the Sheets case) still works as an identifier.

**Comment by behrman** [comment]
I was referring the the mental model of googlesheets, where we had to call `gs_key()` on the sheet ID to get a the spreadsheet object, which needed to be updated. It sounds as though you've already addressed this issue by building googlesheets4 around the static sheet ID. That's a much better way to go.

With the sheet ID serving the role of the path, to get back to your original question, I think you can mirror the mental model of the `write_*()` functions and have a similar ordering of the arguments with data first. This would make the functions work better in pipes.

**Comment by jennybc** [comment]
The new print method for Sheet IDs should help here. Otherwise, I'm going to sit right unless / until there are concrete proposals for a change.
