### ISSUE TITLE
write_sheet fails when dataframe has no rows (only headers)

### ISSUE THREAD

**Issue by Tadge-Analytics** [tidyverse/googlesheets4#92]
Using write_sheets to upload a tibble with no rows (only headers) fails to upload to googlesheets.

```r
# this works
mtcars %>% 
  slice(1) %>% 
 googlesheets4::write_sheet(ss = "1sgHcFyzvHOB2JewWM-F1p8hdLOhugB8pTzrgAwRfgYI", sheet = "test")


# this doesn't work
mtcars %>% 
  slice(0) %>% 
 googlesheets4::write_sheet(ss = "1sgHcFyzvHOB2JewWM-F1p8hdLOhugB8pTzrgAwRfgYI", sheet = "test")
```

Results in the following error:

Error: Client error: (400) INVALID_ARGUMENT
  * Client specified an invalid argument. Check error message and error details for more information.
  * Invalid requests[1].updateSheetProperties: Sorry, it is not possible to delete all non-frozen rows.

**Comment by jennybc** [comment]
I get a slightly different error:

```
Error: Client error: (400) INVALID_ARGUMENT
  * Client specified an invalid argument. Check error message and error details for more information.
  * Invalid requests[1].updateSheetProperties: You can't freeze all visible rows on the sheet.
```

Can you show me the code that creates your test Sheet and the "test" worksheet within it?

While I accept that I need to think about this case of a 0-row data frame, you might also like to know that you can write data into the first row of a sheet with `sheets_edit()` now. And that data could be column headers. See the `sheets_edit()` example about "send data of disparate types to a 1-row rectangle".

The 0-row data frame is problematic for the `sheets_write()` mentality because we try to style the data we send as a table, including freezing the top row. And it's clear from the error I see that you can't freeze the top row if it's the only row.

**Comment by jennybc** [comment]
OK I found a nice way to deal with this, that sets you up for future happiness with `sheets_append()`.

Install the **most recent dev version** of googlesheets4 and enjoy!

``` r
library(tidyverse)
library(googlesheets4)

sheets_auth(email = "jenny@rstudio.com")

ss <- sheets_create(sheets = "test")

mtcars %>%
  slice(0) %>% 
  write_sheet(ss, sheet = "test")
#> Writing to 'cranky-bee'
#> Writing to sheet 'test'

# column headers are there, properly styled, and an empty data row
sheets_browse(ss)

# the first time we append, the empty row gets "used up"
# but we still get to enjoy all the desirable table styling from sheets_write()
sheets_append(slice(mtcars, 1), ss)
#> Writing to 'cranky-bee'
#> Appending 1 row(s) to 'test'

# more appends let you see that the first row is indeed frozen
sheets_append(mtcars, ss)
#> Writing to 'cranky-bee'
#> Appending 32 row(s) to 'test'
sheets_append(mtcars, ss)
#> Writing to 'cranky-bee'
#> Appending 32 row(s) to 'test'
sheets_append(mtcars, ss)
#> Writing to 'cranky-bee'
#> Appending 32 row(s) to 'test'
```

<sup>Created on 2020-02-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
